### ISSUE TITLE
Box截图识别报错

### ISSUE THREAD

**Issue by xhl6666** [CJowo/pcr-guild-django#12]
多次测试可复现
报错的图片链接:
[报错1](https://cdn.img.purinbot.bmfnfx.cn/wp-content/uploads/2020/07/Screenshot_2020-07-28-00-26-48-729_com.bilibili.p.jpg)
[报错2](https://cdn.img.purinbot.bmfnfx.cn/wp-content/uploads/2020/07/Screenshot_2020-07-28-00-26-56-277_com.bilibili.p.jpg)
可以识别的图片链接:
[可识别1](https://cdn.img.purinbot.bmfnfx.cn/wp-content/uploads/2020/07/Screenshot_2020-07-28-00-26-41-620_com.bilibili.p.jpg)
[可识别2](https://cdn.img.purinbot.bmfnfx.cn/wp-content/uploads/2020/07/KHP2@SX22IO4@OOSK.png)
报错内容
`Internal Server Error: /api/character/image
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./pcr/utils.py", line 43, in wrapper
    return func(request, *args, **kwargs)
  File "./pcr/utils.py", line 27, in wrapper
    return func(request, *args, **kwargs)
  File "./character/views.py", line 170, in image
    return HttpResponse(json.dumps(box.characters), content_type='application/json')
  File "./character/utils.py", line 84, in characters
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./character/utils.py", line 94, in character
    star = self.__star(image_cut)
  File "./character/utils.py", line 114, in __star
    b, g, r = image[115, 16*(x+1)]
IndexError: index 115 is out of bounds for axis 0 with size 0`

**Comment by CJowo** [comment]
感谢反馈，已经修复
